project:
  type: website
  output-dir: docs

website:
  title: "William Walz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Visualizations
        menu:
          - href: dataviz.qmd
            text: Artist Births
          - href: chocolate.qmd
            text: Chocolate
          - href: text-analysis.qmd
            text: Text Analysis
          - href: project3.qmd
            text: Life Expectancy Comparison
          - href: AmazonBias.qmd
            text: Amazon Biased Robot
          - href: policingdata.qmd
            text: Analyzing US Policing Data
      - href: slideshow.qmd
      - text: Final Presentation
format:
  html:
    theme:
      - Litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual